// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://ytlldcgemvcyxbtibgww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0bGxkY2dlbXZjeXhidGliZ3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzI0NzQsImV4cCI6MjA3MjkwODQ3NH0.xt0XrBxny5r7KSaApsYmCinPXUKDaEDt2f2Bf2XJwbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
